services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64/v8
    container_name: mssql_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Chulbul@2025
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

  crud_api:
    build:
      context: ./CrudApi
      dockerfile: Dockerfile
    container_name: crud_api
    ports:
      - "5001:8080" # External Access for Browser JS
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;User Id=sa;Password=Chulbul@2025;TrustServerCertificate=True;
    depends_on:
      - db
    restart: on-failure # Retries until DB is ready

  crud_webapp:
    build:
      context: ./CrudWebApp
      dockerfile: Dockerfile
    container_name: crud_webapp
    ports:
      - "5002:8080"
    environment:
      - ApiBaseUrl=http://crud_api:8080 # Internal Access for C#
    depends_on:
      - crud_api
    restart: on-failure

volumes:
  mssql_data:
